(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Morning Fernando, Welcome to Coot. 0.8.3")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good morning Fernando,,,. Welcome to Coot")
(set-display-lists-for-maps 0)
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/home/fernando/programs/EasyHybrid/pdbs/1bx4.pdb" 1)
