filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Morning Fernando, Welcome to Coot. 0.8.3")
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good morning Fernando,,,. Welcome to Coot")
set_display_lists_for_maps (0)
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/home/fernando/programs/EasyHybrid/pdbs/1bx4.pdb", 1)
