(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Morning Fernando, Welcome to Coot. 0.8.3")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good morning Fernando,,,. Welcome to Coot")
(set-display-lists-for-maps 0)
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/home/fernando/programs/EasyHybrid/pdbs/1bx4.pdb" 1)
(graphics-molecule-bond-type 0)
(graphics-to-ca-plus-ligands-sec-struct-representation 0)
(graphics-to-b-factor-cas-representation 0)
(graphics-to-ca-representation 0)
(graphics-to-ca-plus-ligands-representation 0)
(graphics-to-rainbow-representation 0)
(graphics-to-rainbow-representation 0)
(graphics-to-ca-representation 0)
(set-colour-by-chain 0)
(graphics-to-sec-struct-bonds-representation 0)
(set-colour-by-molecule 0)
(graphics-to-bonds-representation 0)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/home/fernando/Desktop/step4.3_ion.pdb" 1)
